/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_kherud_llama_LlamaIterator */

#ifndef _Included_de_kherud_llama_LlamaIterator
#define _Included_de_kherud_llama_LlamaIterator
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
